/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ernesto_RustFeature */

#ifndef _Included_com_ernesto_RustFeature
#define _Included_com_ernesto_RustFeature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ernesto_RustFeature
 * Method:    cryptRC4
 * Signature: ([B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ernesto_RustFeature_cryptRC4
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
